apiVersion: apps/v1
kind: Deployment
metadata:
  name: siodfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siodfs
  template:
    metadata:
      labels:
        app: siodfs
    spec:
      containers:
      - image: okteto.dev/siodfs:latest
        name: siodfs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/siodfs/main/S-html.zip"
        - name: Vless_UUID
          value: "a74a57bf-c1e4-4cdb-9b03-61dfa414b78e"
        - name: Vless_Path
          value: "/vl5dfd55"
        - name: Vmess_UUID
          value: "a74a57bf-c1e4-4cdb-9b03-61dfa414b78e"
        - name: Vmess_Path
          value: "/vm6dsf66"
        - name: Share_Path
          value: "/v2link"
